#!/bin/sh

echo "Running pre-push checks for Supabase..."

UPSTREAM=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null)
if [ -z "$UPSTREAM" ]; then
    echo "No upstream found"
    exit 1
fi

SUPABASE_FILES=$(git diff --name-only --diff-filter=ACM $UPSTREAM...HEAD -- supabase/ | tr '\n' ' ')
if [ -z "$SUPABASE_FILES" ]; then
  echo "No Supabase files changed"
  exit 0
fi

echo "Running deno format check..."
deno fmt -c supabase/deno.json --unstable-sql --check $SUPABASE_FILES || {
  echo "Formatting check failed. Format files before pushing."
  exit 1
}

echo "Running deno type check..."
deno check -c supabase/functions/deno.json supabase/functions