#!/bin/sh

echo "Running pre-push checks for Supabase..."
echo "Running deno format check..."
deno fmt -c supabase/deno.json --unstable-sql --check supabase

echo "Running deno type check..."
deno check -c supabase/functions/deno.json supabase/functions