#!/bin/sh

echo "Running pre-commit checks for Supabase..."
SUPABASE_FILES=$(git diff --cached --name-only --diff-filter=ACM -- supabase/)

if [ -z "$SUPABASE_FILES" ]; then
  echo "No Supabase files changed"
  exit 0
fi

echo "Running deno format..."
deno fmt -c supabase/deno.json --unstable-sql $SUPABASE_FILES
