name: Supabase Migration & Edge Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: v2.x

      - name: Run migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          cd supabase
          supabase link --project-ref $PROJECT_REF
          supabase db push --yes

  typecheck_and_deploy:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: v2.x

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
                    
      - name: Format code
        run: | 
          cd supabase
          deno fmt --check --unstable-sql

      - name: Backup committed DB types
        run: cp ./supabase/functions/_shared/types/database.types.ts /tmp/database.types.backup.ts

      - name: Overwrite DB types with remote
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          cd supabase
          supabase gen types typescript --project-id $PROJECT_REF --schema public > ./functions/_shared/types/database.types.ts

      - name: Check types
        run: |
          cd supabase/functions
          deno check

      - name: Restore committed DB types
        run: mv /tmp/database.types.backup.ts ./supabase/functions/_shared/types/database.types.ts

      - name: Deploy edge functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          cd supabase/functions
          supabase link --project-ref $PROJECT_REF
          supabase functions deploy --no-verify-jwt --yes